### 登录
POST http://localhost:8076/login
Content-Type: application/json

{
  "user": "hello",
  "password": "123456"
}

### 查询人员列表
POST http://localhost:8076/userList
Content-Type: application/json

{
  "page": 1,
  "pageSize": 5
}

### 删除人员
POST http://localhost:8076/deleteUser
Content-Type: application/json

{

}

### 查询人员列表分页
POST http://localhost:8076/userListPage
Content-Type: application/json

{
  "userName": "",
  "page": "1",
  "pageSize": "10"
}

### 更新人员
POST http://localhost:8076/updateUser
Content-Type: application/json

{
  "userName" : "wangbo",
  "password" : "6688",
  "id" : "250ca8ba-089f-4002-b813-4729227cd670"
}
