### 登录
POST http://localhost:8076/login
Content-Type: application/json

{
  "user": "hello",
  "password": "123456"
}

### 查询人员列表
POST http://localhost:8076/userList
Content-Type: application/json

{}

### 删除人员
POST http://localhost:8076/deleteUser
Content-Type: application/json

{

}
